FORMAT: 1A
HOST: http://predictive-emotion-service-api.herokuapp.com

# Predictive Emotion Service

Artificial Intelligence (AI) is already part of our lives. Whenever you pick up
your smartphone, you’re already seeing what AI can do for you, from tailored 
recommendations to relevant search results. With the Salesforce Predictive 
Emotion Service, you can build AI into your Salesforce org or apps without 
needing a Stanford PhD.

The Predictive Emotion Service is part of the Einstein suite of technologies, 
and you can use it to AI-enable your apps. The Predictive Emotion Service takes 
data from heartbeats of a person, learns about how those correlate with that 
person's emotive state, and predicts whether the person is happy, sad, angry, 
or excited to an 87% accuracy.

You can use the service to ascertain mood data from heartbeat data. It analyzes 
small variations in heartbeat intervals to determine levels of emotion.

Out of the box, Predictive Emotion Service already provides datasets for anger,
sadness, excitement, and happiness. More can be added by uploading heartbeat
datasets and labeling with emotions.

## Dataset Collection [/v1/datasets]

Datasets contain heartbeat data associated with an emotion label.

### Create a Dataset [POST]

Create a new dataset with an emotion.

+ Request (application/json)

        {
            "emotion": "happy"
        }

+ Response 201 (application/json)

            {
                "id": 12,
                "createdAt": "2016-11-06T16:51:41.000+0000",
                "updatedAt": "2016-11-06T16:51:41.000+0000",
                "emotion": "happy"
            }
            
+ Response 400 (application/json)

            {
            }

### List Datasets [GET]

List all datasets. Predictive Emotion Service comes with 4 pre-trained
datasets: happy, sad, angry, and excited.

+ Response 200 (application/json)

        [
            {
                "id": 12,
                "createdAt": "2016-11-06T16:51:41.000+0000",
                "updatedAt": "2016-11-06T16:51:41.000+0000",
                "emotion": "happy"
            },
            {
                "id": 13,
                "createdAt": "2016-11-06T20:42:31.000+0000",
                "updatedAt": "2016-11-06T20:42:31.000+0000",
                "emotion": "sad"
            },
            {
                "id": 14,
                "createdAt": "2016-11-06T20:45:02.000+0000",
                "updatedAt": "2016-11-06T20:45:02.000+0000",
                "emotion": "angry"
            },
            {
                "id": 15,
                "createdAt": "2016-11-06T20:58:14.000+0000",
                "updatedAt": "2016-11-06T20:58:14.000+0000",
                "emotion": "excited"
            },
        ]
        
+ Response 400 (application/json)

            {
            }/da